#!/bin/sh

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

read -r -p "Re-build spell index? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
	echo Re-building spell index...
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Spells.csv"
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Bard Spells.csv" --class Bard
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Cleric Spells.csv" --class Cleric
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Druid Spells.csv" --class Druid
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Paladin Spells.csv" --class Paladin
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Ranger Spells.csv" --class Ranger
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Warlock Spells.csv" --class Warlock
	python .git/hooks/utils/spellsConverter.py --from n1300md --to csvIndex -m -p en_US/spells -t "../indices/Wizard & Sorcerer Spells.csv" --class Wizard
	touch .spellIndicesRebuilt
	exit 0
else
	exit 0
fi
